### ISSUE TITLE
 syntax error 

### ISSUE THREAD

**Issue by ipwnosx** [tommytran732/Pterodactyl-Script#46] opened 2021-11-07 12:01 UTC
**Note: for support questions, please use the [Discord](hx)**. This repository's issues are reserved for feature requests and bug reports.

* **I'm submitting a ...**
  - [x ] Bug Report
  - [ ] Feature Request
  - [ ] Support Request => Please do not submit support request here, see note at the top of this template.

* **Do you want to request a *feature* or report a *bug*?**

* **[Pastebin](https://pastebin.com/GKwPz4XW) link of the error**

* **What is the expected behavior?**

* **What is the motivation / use case for changing the behavior?**
 syntax error

* **Please tell us about your environment:**

```
  - Version: vX.X.X
  - OS: [all | Ubuntu 20.04 | Debian XX | CentOS XX | Fedora XX | RedHat XX ]
  - Install Options: [1-22 | Apache, Nginx | Theme ]
```

* **Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by tommytran732** [comment] 2021-11-07 18:11
Duplicate of https://github.com/tommytran732/Pterodactyl-Script/issues/45

**Closed** 2021-11-07 18:11 UTC
