### ISSUE TITLE
too many arguments with auto-deploy command

### ISSUE THREAD

**Issue by ipwnosx** [tommytran732/Pterodactyl-Script#20] opened 2020-11-02 17:01 UTC
cd /etc/pterodactyl && sudo wings configure --panel-url https://labs.prysm.host --token bJT3oUbl3P0K9bAG204qzUMP82lPcXA2roC4EH5ZiXdaGKdJ --node 1
/dev/fd/63: line 1494: cd: too many arguments

**Comment by ipwnosx** [comment] 2020-11-02 17:02
![Screen Shot 2020-11-02 at 10 01 34 AM](https://user-images.githubusercontent.com/41032246/97896532-707f8200-1cf2-11eb-9d98-3fde1dd2a107.png)

**Comment by ryantechdev** [comment] 2020-11-04 22:45
#15

**Comment by tommytran732** [comment] 2020-11-07 06:55
Duplicate of #15 . I will fix this soon.

**Closed by tommytran732** 2020-11-07 06:55 UTC
