### ISSUE TITLE
Maybe bug

### ISSUE THREAD

**Issue by PlesCZ** [tommytran732/Pterodactyl-Script#3] opened 2020-06-25 23:51 UTC
OS: Ubuntu 18.04
If I want to install phpMyAdmin, I have to write the number 11 twice in SSH
![unknown](https://user-images.githubusercontent.com/35809541/85806502-829f5180-b74f-11ea-9530-60745cc43c89.png)

**Comment by PlesCZ** [comment] 2020-06-25 23:53
and twice number 15 too :D

**Comment by tommytran732** [comment] 2020-06-26 06:25
I am unable to reproduce this problem. I don't see anything in the code that could have caused it either. This is likely an issue with your SSH client :/

I am going to close this report. If anyone else has the same issue, feel free to reopen it.

**Closed by tommytran732** 2020-06-26 06:25 UTC
